package com.example.demo.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class BetTypeKeyEnCache {

    private static List<BetType> cache = new ArrayList<>();

    static {
        cache.add(new BetType("1" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("2" , Arrays.asList(new BetTypeKey("h", "Odd"), new BetTypeKey("a", "Even "))));
        cache.add(new BetType("3" , Arrays.asList(new BetTypeKey("h", "Over"), new BetTypeKey("a", "Under"))));
        cache.add(new BetType("5" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("7" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("8" , Arrays.asList(new BetTypeKey("h", "Over"), new BetTypeKey("a", "Under"))));
        cache.add(new BetType("12" , Arrays.asList(new BetTypeKey("h", "Odd"), new BetTypeKey("a", "Even "))));
        cache.add(new BetType("13" , Arrays.asList(new BetTypeKey("hy", "Home Yes "), new BetTypeKey("hn", "Home No"), new BetTypeKey("ay", "Away Yes"), new BetTypeKey("an", "Away No"))));
        cache.add(new BetType("15" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("17" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("18" , Arrays.asList(new BetTypeKey("h", "Over"), new BetTypeKey("a", "Under"))));
        cache.add(new BetType("20" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("21" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("22/160" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "No Goals"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("24" , Arrays.asList(new BetTypeKey("1x", "Home or Draw "), new BetTypeKey("12", "Home or Away"), new BetTypeKey("2x", "Away or Draw"))));
        cache.add(new BetType("25" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("26" , Arrays.asList(new BetTypeKey("o", "One"), new BetTypeKey("n", "No Goal "), new BetTypeKey("b", "Both "))));
        cache.add(new BetType("27" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("28" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("121" , Arrays.asList(new BetTypeKey("x", "Draw"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("122" , Arrays.asList(new BetTypeKey("h", "Home "), new BetTypeKey("x", "Draw"))));
        cache.add(new BetType("123" , Arrays.asList(new BetTypeKey("h", "Draw"), new BetTypeKey("a", "No Draw"))));
        cache.add(new BetType("124" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("125" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("128" , Arrays.asList(new BetTypeKey("oo", "Odd/OddEven "), new BetTypeKey("oe", "Odd/Even"), new BetTypeKey("eo", "Even/Odd"), new BetTypeKey("ee", "Even/Even"))));
        cache.add(new BetType("135" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("143" , Arrays.asList(new BetTypeKey("ho", "Home/Over"), new BetTypeKey("hu", "Home/Under"), new BetTypeKey("do", "Draw/Over"), new BetTypeKey("du", "Draw/Under"), new BetTypeKey("ao", "Away/Over"), new BetTypeKey("au", "Away/Under"))));
        cache.add(new BetType("144/163" , Arrays.asList(new BetTypeKey("hu", "Home/Under"), new BetTypeKey("ho", "Home/Over "), new BetTypeKey("du", "Draw/Under"), new BetTypeKey("do", "Draw/Over"), new BetTypeKey("au", "Away/Under"), new BetTypeKey("ao", "Away/Over"))));
        cache.add(new BetType("145" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("153" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("154" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("155" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("156" , Arrays.asList(new BetTypeKey("O", "Over"), new BetTypeKey("U", "Under"))));
        cache.add(new BetType("157" , Arrays.asList(new BetTypeKey("h", "Odd"), new BetTypeKey("a", "Even "))));
        cache.add(new BetType("1301" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("1302" , Arrays.asList(new BetTypeKey("20", "2-0 "), new BetTypeKey("21", "2-1 "), new BetTypeKey("02", "0-2"), new BetTypeKey("12", "1-2 "))));
        cache.add(new BetType("1303" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("1305" , Arrays.asList(new BetTypeKey("h", "Odd"), new BetTypeKey("a", "Even "))));
        cache.add(new BetType("1306" , Arrays.asList(new BetTypeKey("O", "Over"), new BetTypeKey("U", "Under"))));
        cache.add(new BetType("1308" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("1311" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("1312" , Arrays.asList(new BetTypeKey("O", "Over"), new BetTypeKey("U", "Under"))));
        cache.add(new BetType("1316" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("1318" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("1324" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("164" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "None"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("167" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("168" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("170" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("b", "Both"), new BetTypeKey("n", "None"))));
        cache.add(new BetType("173" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("174" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("175" , Arrays.asList(new BetTypeKey("hr", "Home / FT"), new BetTypeKey("he", "Home / OT"), new BetTypeKey("hp", "Home / PENALTY"), new BetTypeKey("ar", "Away / FT"), new BetTypeKey("ae", "Away / OT"), new BetTypeKey("ap", "Away/ PENALTY"))));
        cache.add(new BetType("176" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("178" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("179" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals"), new BetTypeKey("g4", "4 Goals&Over"))));
        cache.add(new BetType("180" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "None"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("181" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals&Over"))));
        cache.add(new BetType("182" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals&Over"))));
        cache.add(new BetType("187" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals&Over"))));
        cache.add(new BetType("194" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("197" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("198" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("203" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("204" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("205" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("206" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "None"))));
        cache.add(new BetType("207" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "None"))));
        cache.add(new BetType("208" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "None"))));
        cache.add(new BetType("209" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "None"))));
        cache.add(new BetType("210" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("211" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("212" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("213" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("214" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("215" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("219" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("220" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("223" , Arrays.asList(new BetTypeKey("1", "None "), new BetTypeKey("2", "Goal "), new BetTypeKey("4", "corner"), new BetTypeKey("8", "free-kick "), new BetTypeKey("16", "Goal-kick "), new BetTypeKey("32", "throw-in "))));
        cache.add(new BetType("224" , Arrays.asList(new BetTypeKey("1", "None "), new BetTypeKey("2", "Goal"), new BetTypeKey("4", "corner "), new BetTypeKey("64", "booking "), new BetTypeKey("128", "penalty"))));
        cache.add(new BetType("225" , Arrays.asList(new BetTypeKey("1", "No "), new BetTypeKey("44", "Yes"))));
        cache.add(new BetType("226" , Arrays.asList(new BetTypeKey("26", "Goal / Free kick / Goal kick"), new BetTypeKey("36", "Corner / Throw in"), new BetTypeKey("1", "None "))));
        cache.add(new BetType("227" , Arrays.asList(new BetTypeKey("194", "Goal / Booking / Penalty "), new BetTypeKey("4", "Corner "), new BetTypeKey("1", "None"))));
        cache.add(new BetType("376" , Arrays.asList(new BetTypeKey("hg", "Home Goal"), new BetTypeKey("hm", "Home No Goal"), new BetTypeKey("ag", "Away Goal"), new BetTypeKey("am", "Away No Goal"))));
        cache.add(new BetType("381" , Arrays.asList(new BetTypeKey("s", "Goal"), new BetTypeKey("m", "No Goal"))));
        cache.add(new BetType("382" , Arrays.asList(new BetTypeKey("s", "Goal"), new BetTypeKey("m", "No Goal"))));
        cache.add(new BetType("383" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("384" , Arrays.asList(new BetTypeKey("b", "Both"), new BetTypeKey("o", "One"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("385" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("386" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("387" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("388" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("389" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("390" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("391" , Arrays.asList(new BetTypeKey("g4", "0-4 Goals"), new BetTypeKey("g5", "5 Goals"), new BetTypeKey("g6", "6 Goals"), new BetTypeKey("g7", "7 Goals"), new BetTypeKey("g8", "8 Goals"), new BetTypeKey("g9+", "9 Goals&Over"))));
        cache.add(new BetType("392" , Arrays.asList(new BetTypeKey("hAos", "Home Aos"), new BetTypeKey("aAos", "Away Aos"))));
        cache.add(new BetType("393" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("394" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("395" , Arrays.asList(new BetTypeKey("s", "Shot"), new BetTypeKey("h", "Header"), new BetTypeKey("p", "Penalty"), new BetTypeKey("fk", "Free kick"), new BetTypeKey("og", "Own Goal"), new BetTypeKey("ng", "No Goal"))));
        cache.add(new BetType("396" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("397" , Arrays.asList(new BetTypeKey("h1", "Win 1"), new BetTypeKey("a1-", "Win 1"), new BetTypeKey("d", "Draw"), new BetTypeKey("ng", "No Goal"))));
        cache.add(new BetType("398" , Arrays.asList(new BetTypeKey("1x", "Home/Draw"), new BetTypeKey("12", "Home/Away "), new BetTypeKey("2x", "Away/Draw "))));
        cache.add(new BetType("3901" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3902" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("3903" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3904" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3905" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("3906" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("3907" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("3908" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("3909" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3911" , Arrays.asList(new BetTypeKey("h2", "Win 2 "), new BetTypeKey("h3-4", "Win 2 "), new BetTypeKey("a2", "Win2 "), new BetTypeKey("a3-4", "Win 3-4 "))));
        cache.add(new BetType("3912" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3913" , Arrays.asList(new BetTypeKey("ho", "Home/Over "), new BetTypeKey("hu", "Home/Under"), new BetTypeKey("ao", "Away/Over"), new BetTypeKey("au", "Away/Under"))));
        cache.add(new BetType("3914" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("3915" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("d", "Draw"))));
        cache.add(new BetType("3916" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("3918" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("400" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("401" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("402" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("403" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("404" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("406/159" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals"), new BetTypeKey("g4", "4 Goals"), new BetTypeKey("g5", "5 Goals"), new BetTypeKey("g6", "6&Over"))));
        cache.add(new BetType("407/161" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals&Over"))));
        cache.add(new BetType("409/162" , Arrays.asList(new BetTypeKey("g0", "0 Goals"), new BetTypeKey("g1", "1 Goal"), new BetTypeKey("g2", "2 Goals"), new BetTypeKey("g3", "3 Goals&Over"))));
        cache.add(new BetType("410/151" , Arrays.asList(new BetTypeKey("1x", "Home/Draw "), new BetTypeKey("2x", "Away/Draw"), new BetTypeKey("12", "Home/Away"))));
        cache.add(new BetType("411/191" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("412" , Arrays.asList(new BetTypeKey("0", "No Goal"), new BetTypeKey("1", "1 Goal"), new BetTypeKey("2", "2 Goals"), new BetTypeKey("3-Over", "3-Over"))));
        cache.add(new BetType("415/172" , Arrays.asList(new BetTypeKey("hh", "Home/Home"), new BetTypeKey("ha", "Home/Away"), new BetTypeKey("dh", "Draw/Home"), new BetTypeKey("ah", "Away/Home"), new BetTypeKey("aa", "Away/Away"), new BetTypeKey("da", "Draw/Away"), new BetTypeKey("no", "None"))));
        cache.add(new BetType("417" , Arrays.asList(new BetTypeKey("yh", "Yes/Home"), new BetTypeKey("ya", "Yes/Away"), new BetTypeKey("yd", "Yes/Draw"), new BetTypeKey("nh", "No/Home"), new BetTypeKey("na", "No/Away"), new BetTypeKey("nd", "No/Draw"))));
        cache.add(new BetType("418" , Arrays.asList(new BetTypeKey("yo", "Yes/Over"), new BetTypeKey("yu", "Yes/Under"), new BetTypeKey("no", "No/Over"), new BetTypeKey("nu", "No/Under"))));
        cache.add(new BetType("419" , Arrays.asList(new BetTypeKey("1h", "1st half"), new BetTypeKey("2h", "2nd half"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("420" , Arrays.asList(new BetTypeKey("1h", "1st half"), new BetTypeKey("2h", "2nd half"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("421" , Arrays.asList(new BetTypeKey("1h", "1st half"), new BetTypeKey("2h", "2nd half"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("422" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("423" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("424" , Arrays.asList(new BetTypeKey("s", "Shot"), new BetTypeKey("h", "Header"), new BetTypeKey("p", "Penalty"), new BetTypeKey("fk", "Free kick"), new BetTypeKey("og", "Own Goal"), new BetTypeKey("ng", "No Goal"))));
        cache.add(new BetType("425" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("427/188" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("428/184" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("429" , Arrays.asList(new BetTypeKey("0", "No Goal"), new BetTypeKey("1", "1 Goal"), new BetTypeKey("2", "2 Goals (进 2 球)"), new BetTypeKey("3-Over", "3-Over (进3球以上)"))));
        cache.add(new BetType("430/177" , Arrays.asList(new BetTypeKey("1", "2H.Home"), new BetTypeKey("X", "2H.Draw"), new BetTypeKey("2", "2H.Away"))));
        cache.add(new BetType("431/186" , Arrays.asList(new BetTypeKey("HD", "Home/Draw"), new BetTypeKey("HA", "Home/Away"), new BetTypeKey("DA", "Draw/Away"))));
        cache.add(new BetType("432/185" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("433/146" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("434/189" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("435/190" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("436" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("437/148" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("438/133" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("439/134" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("440/149" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("441/150" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("442/140" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"), new BetTypeKey("Tie", "Tie"))));
        cache.add(new BetType("443/141" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"), new BetTypeKey("Tie", "Tie"))));
        cache.add(new BetType("444/142" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"), new BetTypeKey("Tie", "Tie"))));
        cache.add(new BetType("445" , Arrays.asList(new BetTypeKey("yy", "Yes/Yes"), new BetTypeKey("yn", "Yes/No"), new BetTypeKey("ny", "No/Yes"), new BetTypeKey("nn", "No/No"))));
        cache.add(new BetType("446" , Arrays.asList(new BetTypeKey("yy", "Yes/Yes"), new BetTypeKey("yn", "Yes/No"), new BetTypeKey("ny", "No/Yes"), new BetTypeKey("nn", "No/No"))));
        cache.add(new BetType("447" , Arrays.asList(new BetTypeKey("yy", "Yes/Yes"), new BetTypeKey("yn", "Yes/No"), new BetTypeKey("ny", "No/Yes"), new BetTypeKey("nn", "No/No"))));
        cache.add(new BetType("448" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("ng", "No Goal"))));
        cache.add(new BetType("449" , Arrays.asList(new BetTypeKey("1xo", "Home/Draw & Over"), new BetTypeKey("1xu", "Home/Draw & Under"), new BetTypeKey("12o", "Home/Away & Over"), new BetTypeKey("12u", "Home/Away & Under"), new BetTypeKey("2xo", "Away/Draw & Over"), new BetTypeKey("2xu", "Away/Draw & Under"))));
        cache.add(new BetType("450" , Arrays.asList(new BetTypeKey("oo", "odd & Over"), new BetTypeKey("ou", "odd & Under"), new BetTypeKey("eo", "even & Over"), new BetTypeKey("eu", "even & Under"))));
        cache.add(new BetType("451" , Arrays.asList(new BetTypeKey("y1x", "Yes & Home/Draw"), new BetTypeKey("y12", "Yes & Home/Away"), new BetTypeKey("y2x", "Yes & Away/Draw"), new BetTypeKey("n1x", "No & Home/Draw"), new BetTypeKey("n12", "No & Home/Away"), new BetTypeKey("n2x", "No & Away/Draw"))));
        cache.add(new BetType("452" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"))));
        cache.add(new BetType("453" , Arrays.asList(new BetTypeKey("1", "Home"), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("456" , Arrays.asList(new BetTypeKey("yh", "Yes/Home"), new BetTypeKey("ya", "Yes/Away"), new BetTypeKey("yd", "Yes/Draw"), new BetTypeKey("nh", "No/Home"), new BetTypeKey("na", "No/Away"), new BetTypeKey("nd", "No/Draw"))));
        cache.add(new BetType("457" , Arrays.asList(new BetTypeKey("yo", "Yes/Over"), new BetTypeKey("yu", "Yes/Under"), new BetTypeKey("no", "No/Over"), new BetTypeKey("nu", "No/Under"))));
        cache.add(new BetType("460" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("461" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("462" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("463" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("464" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("467" , Arrays.asList(new BetTypeKey("g0/g0", "HT 0 / FT 0"), new BetTypeKey("g0/g1", "HT 0 / FT 1"), new BetTypeKey("g0/g2", "HT 0 / FT 2"), new BetTypeKey("g0/g3", "HT 0 / FT 3"), new BetTypeKey("g0/g4", "HT 0 / FT 4"), new BetTypeKey("g0/g5", "HT 0 / FT 5"), new BetTypeKey("g0/g6", "HT 0 / FT 6"), new BetTypeKey("g0/g7+", "HT 0 / FT 7+"))));
        cache.add(new BetType("468" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("469" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("470" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("471" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("472" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("475" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("e", "exact"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("476" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("e", "exact"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("477" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("478" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("479" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("481" , Arrays.asList(new BetTypeKey("Y", "Yes"), new BetTypeKey("N", "No"))));
        cache.add(new BetType("482" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("483" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("484" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("485" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("486" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("487" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"), new BetTypeKey("n", "Neither"))));
        cache.add(new BetType("488" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("489" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("490" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("491" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("492" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("493" , Arrays.asList(new BetTypeKey("0/0", "HT 0 / FT 0"), new BetTypeKey("0/1", "HT 0 / FT 1"), new BetTypeKey("0/2", "HT 0 / FT 2"), new BetTypeKey("0/3", "HT 0 / FT 3"), new BetTypeKey("0/4", "HT 0 / FT 4"), new BetTypeKey("0/5", "HT 0 / FT 5"), new BetTypeKey("0/6", "HT 0 / FT 6"), new BetTypeKey("0/7+", "HT 0 / FT 7+"))));
        cache.add(new BetType("496" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"), new BetTypeKey("Tie", "Tie"))));
        cache.add(new BetType("497" , Arrays.asList(new BetTypeKey("1h", "First Half"), new BetTypeKey("2h", "Second Half"))));
        cache.add(new BetType("501" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("601" , Arrays.asList(new BetTypeKey("h1-2", "Win 1-2 "), new BetTypeKey("a12-", "Win 1-2 "))));
        cache.add(new BetType("602" , Arrays.asList(new BetTypeKey("h1-2", "Win 1-2 "), new BetTypeKey("a12-", "Win 1-2 "))));
        cache.add(new BetType("603" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("604" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("605" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("606" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("607" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("608" , Arrays.asList(new BetTypeKey("h1-2", "Win 1-2 "), new BetTypeKey("a12-", "Win 1-2 "), new BetTypeKey("d", "Draw"))));
        cache.add(new BetType("609" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("610" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("611" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even"))));
        cache.add(new BetType("612" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("613" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("614" , Arrays.asList(new BetTypeKey("h1-2", "Win 1-2 "), new BetTypeKey("a12-", "Win 1-2 "), new BetTypeKey("d", "Draw"))));
        cache.add(new BetType("615" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("616" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("617" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("630" , Arrays.asList(new BetTypeKey("1", "Home "), new BetTypeKey("x", "Draw"), new BetTypeKey("2", "Away"))));
        cache.add(new BetType("631" , Arrays.asList(new BetTypeKey("hd", "Home/Draw "), new BetTypeKey("da", "Draw/Away "), new BetTypeKey("ha", "Home/Away "))));
        cache.add(new BetType("632" , Arrays.asList(new BetTypeKey("oooo", "Odd/Odd/Odd/Odd "), new BetTypeKey("oooe", "Odd/Odd/Odd/Even "), new BetTypeKey("ooeo", "Odd/Odd/Even/Odd "), new BetTypeKey("oeoo", "Odd/Even/Odd/Odd "), new BetTypeKey("eooo", "Even/Odd/Odd/Odd "), new BetTypeKey("eeee", "Even/Even/Even/Even "), new BetTypeKey("eeeo", "Even/Even/Even/Odd "), new BetTypeKey("eeoe", "Even/Even/Odd/Even"), new BetTypeKey("eoee", "Even/Odd/Even/Even "), new BetTypeKey("oeee", "Odd/Even/Even/Even "), new BetTypeKey("ooee", "Odd/Odd/Even/Even"), new BetTypeKey("oeoe", "Odd/Even/Odd/Even "), new BetTypeKey("eoeo", "Even/Odd/Even/Odd"), new BetTypeKey("eeoo", "Even/Even/Odd/Odd "), new BetTypeKey("eooe", "Even/Odd/Odd/Even"), new BetTypeKey("oeeo", "Odd/Even/Even/Odd "))));
        cache.add(new BetType("633" , Arrays.asList(new BetTypeKey("hh", "Home/Home"), new BetTypeKey("hd", "Home/Draw "), new BetTypeKey("ha", "Home/Away "), new BetTypeKey("dh", "Draw/Home "), new BetTypeKey("dd", "Draw/Draw "), new BetTypeKey("da", "Draw/Away "), new BetTypeKey("ah", "Away/Home "), new BetTypeKey("ad", "Away/Draw "), new BetTypeKey("aa", "Away/Away"))));
        cache.add(new BetType("634" , Arrays.asList(new BetTypeKey("hh", "Home/Home"), new BetTypeKey("hd", "Home/Draw "), new BetTypeKey("ha", "Home/Away "), new BetTypeKey("dh", "Draw/Home "), new BetTypeKey("dd", "Draw/Draw "), new BetTypeKey("da", "Draw/Away "), new BetTypeKey("ah", "Away/Home "), new BetTypeKey("ad", "Away/Draw "), new BetTypeKey("aa", "Away/Away"))));
        cache.add(new BetType("635" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("636" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("637" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("638" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("639" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("640" , Arrays.asList(new BetTypeKey("0", "None"), new BetTypeKey("1", "More than one quarters"))));
        cache.add(new BetType("641" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("642" , Arrays.asList(new BetTypeKey("h12", "1/2 "), new BetTypeKey("h13", "1/3 "), new BetTypeKey("a12", "1/2 "), new BetTypeKey("a13", "1/3 "), new BetTypeKey("Aos12", " AOS 1/2 "))));
        cache.add(new BetType("643" , Arrays.asList(new BetTypeKey("1q", "Quarter 1 "), new BetTypeKey("2q", "Quarter 2 "), new BetTypeKey("3q", "Quarter 3 "), new BetTypeKey("4q", "Quarter 4 "), new BetTypeKey("Tie", "Tie "))));
        cache.add(new BetType("645" , Arrays.asList(new BetTypeKey("hh", "Home/Home"), new BetTypeKey("hd", "Home/Draw "), new BetTypeKey("ha", "Home/Away "), new BetTypeKey("dh", "Draw/Home "), new BetTypeKey("dd", "Draw/Draw "), new BetTypeKey("da", "Draw/Away "), new BetTypeKey("ah", "Away/Home "), new BetTypeKey("ad", "Away/Draw "), new BetTypeKey("aa", "Away/Away"))));
        cache.add(new BetType("646" , Arrays.asList(new BetTypeKey("ho", "Home/Over "), new BetTypeKey("hu", "Home/Under"), new BetTypeKey("ao", "Away/Over"), new BetTypeKey("au", "Away/Under"))));
        cache.add(new BetType("701" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("702" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("704" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("705" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("706" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("707" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("708" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("709" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("710" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("711" , Arrays.asList(new BetTypeKey("h1-2", "Win 1-2 "), new BetTypeKey("a12-", "Win 1-2 "))));
        cache.add(new BetType("712" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("713" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("714" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));
        cache.add(new BetType("9001" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9002" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9003" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9004" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9005" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9006" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9007" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9008" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9009" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9010" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9011" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9012" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9013" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9014" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9015" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9016" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9017" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9018" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9019" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9020" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9021" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9024" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9025" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9026" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9027" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9028" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9029" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9030" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9031" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9032" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9033" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9035" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9036" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9037" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9038" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9039" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9040" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9041" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9042" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9043" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9044" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9045" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9046" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9047" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9048" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9049" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9050" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9051" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9052" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9053" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9054" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9055" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9056" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9057" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9058" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9059" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9060" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9061" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9062" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9063" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9064" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9065" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9066" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9067" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9068" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9069" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9070" , Arrays.asList(new BetTypeKey("o", "Over"), new BetTypeKey("u", "Under"))));
        cache.add(new BetType("9071" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9072" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9073" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9077" , Arrays.asList(new BetTypeKey("h", "Home"), new BetTypeKey("a", "Away"))));
        cache.add(new BetType("9078" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9079" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9080" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9081" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9082" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9083" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9084" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9085" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9086" , Arrays.asList(new BetTypeKey("o", "Odd"), new BetTypeKey("e", "Even "))));
        cache.add(new BetType("9087" , Arrays.asList(new BetTypeKey("y", "Yes"), new BetTypeKey("n", "No"))));

    }

    public static  String findBetTypeKey(String betType, String key) {
        Optional<BetType> first = cache.stream().filter(it -> it.getBetType().equals(betType)).findFirst();

        if (!first.isPresent()) {
            return null;
        }

        for (BetTypeKey betTypeKey : first.get().getBetTypeKey()) {
            if (betTypeKey.getKey().equals(key)) {
                return betTypeKey.getEnValue();
            }
        }
        return null;
    }
}
